#!/bin/bash
touch wrong_input_testing.log
clear
(
#Test 1 - unexpected arguments:
echo ""
echo "********************************************************************************"
echo "                      Test 1: [N] integer, but 1st argument unexpected"
echo " Used arguments:"
echo " ../debug/Lab3_2 -o 12 test_file"
echo "********************************************************************************"
echo ""
echo " Terminal out: "
echo ""
../debug/Lab3_2 -o 12 test_file
echo " Press any key to continue: "
read -n 1

#Test 2 - unexpected arguments:
echo ""
echo "********************************************************************************"
echo "                         Test 2: [N] argument not an integer"
echo " Used arguments:"
echo " ../debug/Lab3_2 -o qweqwe 123"
echo "********************************************************************************"
echo ""
echo " Terminal out: "
echo ""
../debug/Lab3_2 -o openmode 123
echo " Press any key to continue: "
read -n 1

#Test 3 - unexpected arguments:
echo ""
echo "********************************************************************************"
echo "                  Test 3: [N] argument less then or equal to 0"
echo "********************************************************************************"
echo " 3.1) Used arguments:"
echo " ../debug/Lab3_2 -c -123 test_file"
echo "********************************************************************************"
echo ""
echo " Terminal out: "
../debug/Lab3_2 -c -123 test_file
echo " Press any key to continue: "
read -n 1
echo ""
echo "********************************************************************************"
echo " 3.2) Used arguments:"
echo " ../debug/Lab3_2 -r 0 test_file"
echo "********************************************************************************"
echo ""
echo " Terminal out: "
echo ""
../debug/Lab3_2 -r 0 test_file
echo " Press any key to continue: "
read -n 1

#Test 4 - [N] is float
echo ""
echo "********************************************************************************"
echo "                      Test 4: [N] is floating point number"
echo "********************************************************************************"
echo " 4.1) Used arguments:"
echo " ../debug/Lab3_2 -c 3.2 test_file"
echo "********************************************************************************"
echo ""
echo " Terminal out: "
../debug/Lab3_2 -c 3.2 test_file
echo " Press any key to continue: "
read -n 1
echo ""
echo "********************************************************************************"
echo " 4.2) Used arguments:"
echo " ../debug/Lab3_2 -c 3,2 test_file"
echo "********************************************************************************"
echo ""
echo " Terminal out: "
../debug/Lab3_2 -c 3,2 test_file
echo " Press any key to continue: "
read -n 1

#Test 5 - unable to create or open file
echo ""
echo "********************************************************************************"
echo "                      Test 5: Trying to open file that doesn't exist "
echo " Used arguments:"
echo " ../debug/Lab3_2 -r 5 qweqweqweqw"
echo "********************************************************************************"
echo ""
echo " Terminal out: "
../debug/Lab3_2 -r 5 qweqweqweqw
echo " Press any key to continue: "
read -n 1

#Test 6 - empty file
echo ""
echo "********************************************************************************"
echo "                      Test 6: Trying to read empty file"
echo " Used arguments:"
echo " ../debug/Lab3_2 -r 5 empty_file"
echo "********************************************************************************"
echo ""
echo " Terminal out: "
../debug/Lab3_2 -r 5 empty_file
echo " Press any key to continue: "
read -n 1

#Test 7 - wrong file
echo ""
echo "********************************************************************************"
echo "           Test 7: Trying to open a file created in another application"
echo " Used arguments:"
echo " ../debug/Lab3_2 -r 5 wrong_file"
echo "********************************************************************************"
echo ""
echo " Terminal out: "
../debug/Lab3_2 -r 5 wrong_file
echo " Press any key to continue: "
read -n 1

#Test 8 - wrong arguments:
echo ""
echo "********************************************************************************"
echo "                        Test 8: wrong number of arguments"
echo "********************************************************************************"
echo " 8.1) No arguments.Used arguments:"
echo " ../debug/Lab3_2"
echo "********************************************************************************"
echo ""
echo " Terminal out: "
../debug/Lab3_2
echo " Press any key to continue: "
read -n 1
echo ""
echo "********************************************************************************"
echo " 8.2) To many arguments. Creating. Used arguments:"
echo " ../debug/Lab3_2 -c 12 test_file mode"
echo "********************************************************************************"
echo ""
echo " Terminal out: "
echo ""
../debug/Lab3_2 -c 12 test_file mode
echo " Press any key to continue: "
read -n 1
echo ""
echo "********************************************************************************"
echo " 8.3) Too many arguments. Reading. Used arguments:"
echo " ../debug/Lab3_2 -r 12 test_file mode"
echo "********************************************************************************"
echo ""
echo " Terminal out: "
../debug/Lab3_2 -r 12 test_file mode
echo ""
echo " Testing complete"
echo " Results saved in wrong_input_testing.log"
) | tee wrong_input_testing.log
